all:
	cd .. && make

clean:
	rm -f *.acn
	rm -f *.acr
	rm -f *.alg
	rm -f *.aux
	rm -f *.glg
	rm -f *.glo
	rm -f *.gls
	rm -f *.idx
	rm -f *.ilg
	rm -f *.ild
	rm -f *.ind
	rm -f *.ist
	rm -f *.log
	rm -f *.lof
	rm -f *.lol
	rm -f *.lot
	rm -f *.out
	rm -f *.toc
	rm -f *~
	rm -f .log
	rm -f *.bak
	rm -f *.bck
	rm -f .depend 
	cd .. && make clean

